server:
  port: 8182
spring:
  application:
    name: "auth-server"
  datasource:
    url: jdbc:postgresql://localhost:5432/jobapp
    username: postgres
    password: postgres
  security:
    jwt-secret: "jwt-secret"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true